### ISSUE TITLE
Handle castling's rule

### ISSUE THREAD

**Issue by alessandrodalbello** [chesslave/chesslave#26]
Castlings, both kingside and queenside, are already handled by the `Movement` class, but they are not considered by chess rules. In addition to the adjacent squares, a king can also castle if the conditions subsist.
Add castlings to the set of possible moves of a king.

**Comment by maurocchi** [comment]
I've not yet considered the castling because for our purposes it is not (yet) real necessary. 

On the occurrence, we could be implement a method like `Rules.castling(game)` returning the set of castling moves available, or we could extend `Rules.moves(game, from)`, returning all the moves available (castling included).
